import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem" }}>
          Navbar
        </header>

        <main>{children}</main>

        <footer style={{ backgroundColor: "ghostwhite", padding: "1rem" }}>
          Footer
        </footer>
      </body>
    </html>
  );
}
